# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc45101fbbb2d76e8824dbadecbe1091db8958cc123342da9d9997369e551687055cdf1747e3942963c55c9c53003c611642f5be1e22afd477af80a789b89967

test:
  secret_key_base: 9da5bfea035f116b30ae10d318af5dbea632a6fe231e19dfbcdb8d9430bfa672fd53d977c369d2dcce4f52dee6d0a8325fcda8f0bdfe28208a403a559dd79e03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
